name: Code Quality (Lint & Format)

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  eslint-prettier:
    name: Run Prettier & ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Formatting (Prettier)
        run: pnpm exec prettier --check .

      - name: Run ESLint
        run: pnpm run lint
